ToDo list review for JS best practice checks
charlyeneh/ToDo-List-Partner-Review pull request #1
Opened 2022-02-21 21:28 UTC by charlyeneh

Highlights:-
- A copy of the ToDo list app was created on the feature branch.
- A request for review will be done from my partner.

2022-02-21 23:24 UTC, estebanmual requested changes
Hi Charles, great job doing the activity :fire: 
I loved the design and functionalities you included :100: 

I only have some little suggestions that you can check through the code review.

2022-02-21 23:24 UTC, estebanmual commented on dist/bundle.js
> +;
I would recommend deleting all the comments that appear in the file as it is unnecessary code. You can do this automatically through the optimization of the file within the webpack config file.

2022-02-21 23:24 UTC, estebanmual commented on src/index.html
> +    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
A good practice to follow is that in the template file we declare in webpack, we should not include any link tag or script tag. My suggestion is to include them through webpack process.

2022-02-21 23:24 UTC, estebanmual commented on src/index.html
> +<script type ="module" src="index.js"></script>
A good practice to follow is that in the template file we declare in webpack, we should not include any link tag or script tag. My suggestion is to include them through webpack process.

2022-02-25 14:56 UTC, charlyeneh commented
Hi @estebanmual,  
Thank you for your kind reviews.

A look at the above issues raised looks like they are optional changes. I will look into them and update them where necessary.

Best regards and happy coding.

2022-02-26 15:54 UTC, estebanmual approved these changes
Great job Charles! Nothing else to add! 💯 🔥

2022-02-26 20:24 UTC, merged